# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m.xci
# IP: The module: 'pll_50m_to_100m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50m_to_100m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50m_to_100m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50m_to_100m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m.xci
# IP: The module: 'pll_50m_to_100m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50m_to_100m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50m_to_100m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGAmoudle/--main/--main/vivado_project_pl_only/DDS_Signal_Generator_PL/DDS_Signal_Generator_PL.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50m_to_100m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
