# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.cache/wt [current_project]
set_property parent.project_path D:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/FPGAmoudle/--main/--main/rtl/DDS_Core.v
  D:/FPGAmoudle/--main/--main/rtl/DDS_Signal_Generator.v
  D:/FPGAmoudle/--main/--main/rtl/HMI_Recv.v
  D:/FPGAmoudle/--main/--main/rtl/HMI_UARX.v
  D:/FPGAmoudle/--main/--main/rtl/HMI_UATX.v
  D:/FPGAmoudle/--main/--main/rtl/Key_Control.v
  D:/FPGAmoudle/--main/--main/rtl/DDS_Signal_Generator_top.v
}
read_ip -quiet D:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m.xci
set_property used_in_implementation false [get_files -all d:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m.xdc]
set_property used_in_implementation false [get_files -all d:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/sources_1/ip/pll_50m_to_100m/pll_50m_to_100m_ooc.xdc]

add_files D:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/sources_1/bd/zynq_ps/zynq_ps.bd
set_property used_in_implementation false [get_files -all d:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/sources_1/bd/zynq_ps/ip/zynq_ps_ps7_0_1/zynq_ps_ps7_0.xdc]
set_property used_in_implementation false [get_files -all D:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/sources_1/bd/zynq_ps/zynq_ps_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/constrs_1/new/DDS_Signal_Generator.xdc
set_property used_in_implementation false [get_files D:/FPGAmoudle/--main/--main/vivado_project/DDS_Signal_Generator.srcs/constrs_1/new/DDS_Signal_Generator.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top DDS_Signal_Generator_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DDS_Signal_Generator_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DDS_Signal_Generator_top_utilization_synth.rpt -pb DDS_Signal_Generator_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
