# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/DDS_Signal_Generator.xdc

# IP: ip/pll_50m_to_100m/pll_50m_to_100m.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_50m_to_100m || ORIG_REF_NAME==pll_50m_to_100m} -quiet] -quiet

# Block Designs: bd/zynq_ps/zynq_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_ps || ORIG_REF_NAME==zynq_ps} -quiet] -quiet

# IP: bd/zynq_ps/ip/zynq_ps_ps7_0_1/zynq_ps_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_ps_ps7_0 || ORIG_REF_NAME==zynq_ps_ps7_0} -quiet] -quiet

# XDC: ip/pll_50m_to_100m/pll_50m_to_100m_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll_50m_to_100m || ORIG_REF_NAME==pll_50m_to_100m} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll_50m_to_100m/pll_50m_to_100m.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll_50m_to_100m || ORIG_REF_NAME==pll_50m_to_100m} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll_50m_to_100m/pll_50m_to_100m_ooc.xdc

# XDC: bd/zynq_ps/zynq_ps_ooc.xdc
